version: '3'

tasks:
  test:
    summary: Run unit test with logs
    cmds:
      - RUST_LOG=debug cargo test -- --nocapture
  run:
    summary: Run application with hot-reload
    cmds:
      - cargo watch -s 'export $(cat .env | xargs) && cargo run -- -release'
  update_version:
    summary: Update version manifest
    cmds:
      - |
        cat <<EOF> version
        {
          "version": "$(cat cmd/Cargo.toml| grep '^version' | awk -F '=' '{print $2}' | sed 's/[[:space:]|\"]//g')",
          "build_date": "$(date +%F)",
          "build_hash": "$(git rev-parse HEAD)"
        }
        EOF
  compose-run:
    summary: Run application in docker compose with database
    cmds:
      - |
        export $(cat .env | xargs)
        cd build
        docker compose up -d
